stages:
  #- static-test
  #- artifacts
  #- test
  - build
  #- deploy
#include:
#  - template: Container-Scanning.gitlab-ci.yml

##===============Code Quality /Static Testing==========
#sonarqube-pretest:
#   stage: static-test
#   #when: manual
#   #tags: [old-runner]
#   image: sonarsource/sonar-scanner-cli:latest
#   variables:
#       SONAR_TOKEN: "d7f396cb22cd2393410d47834cccdf9fa8b1885d"
#       SONAR_HOST_URL: "http://192.168.1.109:9000"
#       SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar" 
#       GIT_DEPTH: 1
#   script:
#       - pwd
#   cache:
#       key: ${CI_JOB_NAME}
#       paths:
#       - .sonar/cache
#   allow_failure: false
#sonarqube-test:
#   stage: static-test
#   #tags: [old-runner]
#   #when: manual
#   image: sonarsource/sonar-scanner-cli:latest
#   variables:
#       SONAR_TOKEN: "d7f396cb22cd2393410d47834cccdf9fa8b1885d"
#       SONAR_HOST_URL: "http://192.168.1.109:9000"
#       SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar" 
#       GIT_DEPTH: 1
#
#   script:
#       - sonar-scanner -Dsonar.qualitygate.wait=true
#   allow_failure: false
# include:
#  - template: Code-Quality.gitlab-ci.yml

# code_quality:
#    stage: static-test
#    artifacts:
#      expire_in: 1000 yrs
#      expose_as: 'Code Quality Report'
#      paths: [gl-code-quality-report.json]
## ===============================================================


#mvn_artifacts:
#    stage: artifacts
#    #when: manual
#    image: maven:3.6.3
#    script:
##    - yum install maven -y
#    - rm -rf target
#    - ls -ltr
#    - mvn clean
#    - mvn package

#    artifacts:
#        paths:
#            - target
#    allow_failure: false

build-image:
    stage: build
    #when: manual
    image: docker:18.06
    services:
      - docker:dind
    before_script:
      - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    dependencies:
      - mvn_artifacts

    script:
      #- cp -r ./target ./
      - docker build --pull -t "$CI_REGISTRY_IMAGE:${CI_COMMIT_REF_NAME}" .
      - docker push "$CI_REGISTRY_IMAGE:${CI_COMMIT_REF_NAME}"
      
    allow_failure: false


